### ISSUE TITLE
pixel 2.3.1 builder on mac, missing gulp-saas

### ISSUE THREAD

**Issue by amitai52** [smnedelko/PixelAdmin#11]
Builder on MAC, after running in new directory:
`npm run compile`
I Get this error:

> gulp
module.js:327
    throw err;
    ^
Error: Cannot find module 'gulp-sass'
    at Function.Module._resolveFilename (module.js:325:15)

I run:
`npm install`
gulp-saas was missing , and is installed

now the compile works
somehow the builder skipped this dependency?

**Comment by amitai52** [comment]
AND, to add to this, each time I update the package with a new module
it removes gulp-saas, and I have to start over again

I'd appreciate some answer on this ...

**Comment by smnedelko** [comment]
Hi, this is an expected behaviour. Removing gulp-sass is important because builder is bundled with its own version of nodejs, and gulp-sass package is compiled strictly depending on the nodejs version/architecture (you will get an error if you try to compile scss sources using node-sass that compiled with node version different from yours). So I have to remove the package before/after each build.

**Comment by amitai52** [comment]
I think there should be some solution
I have to do `npm install` after each builder update?
isn't builder supposed to take care of that?

**Comment by smnedelko** [comment]
I was thinking about this problem. As a solution, I can rename installed `gulp-sass` package on each build and then, after build process end, rename it back. Using that solution, you will need to run `npm install` command only after first build... I will implement this behaviour in the near time.
